{'aceId': '2E0F8692-724D-4BF3-B384-3E0A47D2CBF8',
 'class': 'Create',
 'group': 'com.apple.ace.note',
 'properties': {'callbacks': [],
                'contents': 'I have to do'},
 'refId': 'A3F6376D-96A9-4CAE-B4AC-D7AC89C66276'}

{'aceId': 'B69371B3-7423-434E-B71B-8E1D496000F4',
 'class': 'AddViews',
 'group': 'com.apple.ace.assistant',
 'properties': {'callbacks': [],
                'dialogPhase': 'Summary',
                'scrollToTop': False,
                'temporary': False,
                'views': [{'class': 'AssistantUtteranceView',
                           'group': 'com.apple.ace.assistant',
                           'properties': {'dialogIdentifier': 'Note#created',
                                          'listenAfterSpeaking': False,
                                          'speakableText': 'Here is your note:',
                                          'text': 'Here is your note:'}},
                          {'class': 'Snippet',
                           'group': 'com.apple.ace.note',
                           'properties': {'notes': [{'class': 'Object',
                                                     'group': 'com.apple.ace.note',
                                                     'properties': {'contents': 'I have to do',
                                                                    'identifier': 'x-coredata://9523080D-0668-4238-8528-C3050D9E0A57/Note/p56'}}]}}]},
 'refId': '1084C9C3-C681-49CD-B274-21783BBBEFB3'}