{'aceId': 'C0150F07-460C-4263-BCEB-EB93650911D2',
 'class': 'AddViews',
 'group': 'com.apple.ace.assistant',
 'properties': {'callbacks': [],
                'dialogPhase': 'Summary',
                'scrollToTop': False,
                'temporary': False,
                'views': [{'class': 'AssistantUtteranceView',
                           'group': 'com.apple.ace.assistant',
                           'properties': {'dialogIdentifier': 'Weather#forecastCommentary',
                                          'listenAfterSpeaking': False,
                                          'speakableText': 'This is the forecast for Jordaan, The Netherlands',
                                          'text': 'This is the forecast for Jordaan, The Netherlands'}},
                          {'class': 'ForecastSnippet',
                           'group': 'com.apple.ace.weather',
                           'properties': {'aceWeathers': [{'class': 'Object',
                                                           'group': 'com.apple.ace.weather',
                                                           'properties': {'currentConditions': {'class': 'CurrentConditions',
                                                                                                'group': 'com.apple.ace.weather',
                                                                                                'properties': {'condition': {'class': 'Condition',
                                                                                                                             'group': 'com.apple.ace.weather',
                                                                                                                             'properties': {'conditionCode': 'MostlyCloudyDay',
                                                                                                                                            'conditionCodeIndex': 28}},
                                                                                                               'dayOfWeek': 3,
                                                                                                               'dewPoint': '0',
                                                                                                               'feelsLike': '0',
                                                                                                               'moonPhase': 'WAXING_GIBBOUS',
                                                                                                               'percentHumidity': '80',
                                                                                                               'percentOfMoonFaceVisible': 90,
                                                                                                               'sunrise': '7:30',
                                                                                                               'sunset': '19:00',
                                                                                                               'temperature': '-5.2',
                                                                                                               'timeOfObservation': '18:00',
                                                                                                               'timeZone': 'Central European Time',
                                                                                                               'visibility': '0',
                                                                                                               'windChill': '0'}},
                                                                          'dailyForecasts': [{'class': 'DailyForecast',
                                                                                              'group': 'com.apple.ace.weather',
                                                                                              'properties': {'chanceOfPerception': 0,
                                                                                                             'condition': {'class': 'Condition',
                                                                                                                           'group': 'com.apple.ace.weather',
                                                                                                                           'properties': {'conditionCode': 'PartlyCloudyDay',
                                                                                                                                          'conditionCodeIndex': 30}},
                                                                                                             'highTemperature': u'-3',
                                                                                                             'isUserRequested': True,
                                                                                                             'lowTemperature': u'-4',
                                                                                                             'timeIndex': 3}},
                                                                                             {'class': 'DailyForecast',
                                                                                              'group': 'com.apple.ace.weather',
                                                                                              'properties': {'chanceOfPerception': 0,
                                                                                                             'condition': {'class': 'Condition',
                                                                                                                           'group': 'com.apple.ace.weather',
                                                                                                                           'properties': {'conditionCode': 'PartlyCloudyDay',
                                                                                                                                          'conditionCodeIndex': 30}},
                                                                                                             'highTemperature': u'-1',
                                                                                                             'isUserRequested': True,
                                                                                                             'lowTemperature': u'-5',
                                                                                                             'timeIndex': 4}},
                                                                                             {'class': 'DailyForecast',
                                                                                              'group': 'com.apple.ace.weather',
                                                                                              'properties': {'chanceOfPerception': 0,
                                                                                                             'condition': {'class': 'Condition',
                                                                                                                           'group': 'com.apple.ace.weather',
                                                                                                                           'properties': {'conditionCode': 'Cloudy',
                                                                                                                                          'conditionCodeIndex': 26}},
                                                                                                             'highTemperature': u'1',
                                                                                                             'isUserRequested': True,
                                                                                                             'lowTemperature': u'-4',
                                                                                                             'timeIndex': 5}},
                                                                                             {'class': 'DailyForecast',
                                                                                              'group': 'com.apple.ace.weather',
                                                                                              'properties': {'chanceOfPerception': 0,
                                                                                                             'condition': {'class': 'Condition',
                                                                                                                           'group': 'com.apple.ace.weather',
                                                                                                                           'properties': {'conditionCode': 'PartlyCloudyDay',
                                                                                                                                          'conditionCodeIndex': 30}},
                                                                                                             'highTemperature': u'-3',
                                                                                                             'isUserRequested': True,
                                                                                                             'lowTemperature': u'-9',
                                                                                                             'timeIndex': 6}},
                                                                                             {'class': 'DailyForecast',
                                                                                              'group': 'com.apple.ace.weather',
                                                                                              'properties': {'chanceOfPerception': 0,
                                                                                                             'condition': {'class': 'Condition',
                                                                                                                           'group': 'com.apple.ace.weather',
                                                                                                                           'properties': {'conditionCode': 'Sunny',
                                                                                                                                          'conditionCodeIndex': 32}},
                                                                                                             'highTemperature': u'-2',
                                                                                                             'isUserRequested': True,
                                                                                                             'lowTemperature': u'-5',
                                                                                                             'timeIndex': 7}},
                                                                                             {'class': 'DailyForecast',
                                                                                              'group': 'com.apple.ace.weather',
                                                                                              'properties': {'chanceOfPerception': 0,
                                                                                                             'condition': {'class': 'Condition',
                                                                                                                           'group': 'com.apple.ace.weather',
                                                                                                                           'properties': {'conditionCode': 'Cloudy',
                                                                                                                                          'conditionCodeIndex': 26}},
                                                                                                             'highTemperature': u'3',
                                                                                                             'isUserRequested': True,
                                                                                                             'lowTemperature': u'-3',
                                                                                                             'timeIndex': 1}}],
                                                                          'extendedForecastUrl': u'http://www.wunderground.com/global/stations/06240.html',
                                                                          'hourlyForecasts': [{'class': 'HourlyForecast',
                                                                                               'group': 'com.apple.ace.weather',
                                                                                               'properties': {'chanceOfPrecipitation': 0,
                                                                                                              'condition': {'class': 'Condition',
                                                                                                                            'group': 'com.apple.ace.weather',
                                                                                                                            'properties': {'conditionCode': 'Sunny',
                                                                                                                                           'conditionCodeIndex': 32}},
                                                                                                              'isUserRequested': True,
                                                                                                              'temperature': u'-4',
                                                                                                              'timeIndex': u'15'}},
                                                                                              {'class': 'HourlyForecast',
                                                                                               'group': 'com.apple.ace.weather',
                                                                                               'properties': {'chanceOfPrecipitation': 0,
                                                                                                              'condition': {'class': 'Condition',
                                                                                                                            'group': 'com.apple.ace.weather',
                                                                                                                            'properties': {'conditionCode': 'MostlyCloudyDay',
                                                                                                                                           'conditionCodeIndex': 28}},
                                                                                                              'isUserRequested': True,
                                                                                                              'temperature': u'-3',
                                                                                                              'timeIndex': u'16'}},
                                                                                              {'class': 'HourlyForecast',
                                                                                               'group': 'com.apple.ace.weather',
                                                                                               'properties': {'chanceOfPrecipitation': 0,
                                                                                                              'condition': {'class': 'Condition',
                                                                                                                            'group': 'com.apple.ace.weather',
                                                                                                                            'properties': {'conditionCode': 'MostlyCloudyDay',
                                                                                                                                           'conditionCodeIndex': 28}},
                                                                                                              'isUserRequested': True,
                                                                                                              'temperature': u'-3',
                                                                                                              'timeIndex': u'17'}},
                                                                                              {'class': 'HourlyForecast',
                                                                                               'group': 'com.apple.ace.weather',
                                                                                               'properties': {'chanceOfPrecipitation': 0,
                                                                                                              'condition': {'class': 'Condition',
                                                                                                                            'group': 'com.apple.ace.weather',
                                                                                                                            'properties': {'conditionCode': 'MostlyCloudyNight',
                                                                                                                                           'conditionCodeIndex': 27}},
                                                                                                              'isUserRequested': True,
                                                                                                              'temperature': u'-3',
                                                                                                              'timeIndex': u'18'}},
                                                                                              {'class': 'HourlyForecast',
                                                                                               'group': 'com.apple.ace.weather',
                                                                                               'properties': {'chanceOfPrecipitation': 5,
                                                                                                              'condition': {'class': 'Condition',
                                                                                                                            'group': 'com.apple.ace.weather',
                                                                                                                            'properties': {'conditionCode': 'MostlyCloudyNight',
                                                                                                                                           'conditionCodeIndex': 27}},
                                                                                                              'isUserRequested': True,
                                                                                                              'temperature': u'-3',
                                                                                                              'timeIndex': u'19'}},
                                                                                              {'class': 'HourlyForecast',
                                                                                               'group': 'com.apple.ace.weather',
                                                                                               'properties': {'chanceOfPrecipitation': 5,
                                                                                                              'condition': {'class': 'Condition',
                                                                                                                            'group': 'com.apple.ace.weather',
                                                                                                                            'properties': {'conditionCode': 'MostlyCloudyNight',
                                                                                                                                           'conditionCodeIndex': 27}},
                                                                                                              'isUserRequested': True,
                                                                                                              'temperature': u'-3',
                                                                                                              'timeIndex': u'20'}},
                                                                                              {'class': 'HourlyForecast',
                                                                                               'group': 'com.apple.ace.weather',
                                                                                               'properties': {'chanceOfPrecipitation': 5,
                                                                                                              'condition': {'class': 'Condition',
                                                                                                                            'group': 'com.apple.ace.weather',
                                                                                                                            'properties': {'conditionCode': 'MostlyCloudyNight',
                                                                                                                                           'conditionCodeIndex': 27}},
                                                                                                              'isUserRequested': True,
                                                                                                              'temperature': u'-4',
                                                                                                              'timeIndex': u'21'}},
                                                                                              {'class': 'HourlyForecast',
                                                                                               'group': 'com.apple.ace.weather',
                                                                                               'properties': {'chanceOfPrecipitation': 5,
                                                                                                              'condition': {'class': 'Condition',
                                                                                                                            'group': 'com.apple.ace.weather',
                                                                                                                            'properties': {'conditionCode': 'ClearNight',
                                                                                                                                           'conditionCodeIndex': 31}},
                                                                                                              'isUserRequested': True,
                                                                                                              'temperature': u'-4',
                                                                                                              'timeIndex': u'22'}},
                                                                                              {'class': 'HourlyForecast',
                                                                                               'group': 'com.apple.ace.weather',
                                                                                               'properties': {'chanceOfPrecipitation': 5,
                                                                                                              'condition': {'class': 'Condition',
                                                                                                                            'group': 'com.apple.ace.weather',
                                                                                                                            'properties': {'conditionCode': 'ClearNight',
                                                                                                                                           'conditionCodeIndex': 31}},
                                                                                                              'isUserRequested': True,
                                                                                                              'temperature': u'-4',
                                                                                                              'timeIndex': u'23'}},
                                                                                              {'class': 'HourlyForecast',
                                                                                               'group': 'com.apple.ace.weather',
                                                                                               'properties': {'chanceOfPrecipitation': 5,
                                                                                                              'condition': {'class': 'Condition',
                                                                                                                            'group': 'com.apple.ace.weather',
                                                                                                                            'properties': {'conditionCode': 'ClearNight',
                                                                                                                                           'conditionCodeIndex': 31}},
                                                                                                              'isUserRequested': True,
                                                                                                              'temperature': u'-3',
                                                                                                              'timeIndex': u'0'}}],
                                                                          'units': {'class': 'Units',
                                                                                    'group': 'com.apple.ace.weather',
                                                                                    'properties': {'distanceUnits': 'Kilometers',
                                                                                                   'pressureUnits': 'MB',
                                                                                                   'speedUnits': 'KPH',
                                                                                                   'temperatureUnits': 'Celsius'}},
                                                                          'view': 'DAILY',
                                                                          'weatherLocation': {'class': 'Location',
                                                                                              'group': 'com.apple.ace.weather',
                                                                                              'properties': {'city': 'Frankfurt',
                                                                                                             'countryCode': 'Germany',
                                                                                                             'locationId': '20066682',
                                                                                                             'stateCode': 'Hesse'}}}}]}}]},
 'refId': '1CBAD235-1A7A-4EB4-816F-7E3282E16DEC'}